# Generated by Django 5.0.4 on 2024-04-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ulid',
            field=models.CharField(blank=True, max_length=26, unique=True, verbose_name='ULID'),
        ),
    ]
