# Generated by Django 5.0.4 on 2024-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='ulid',
            field=models.CharField(default='01HWFK6AKPSYCQDNG3R33QHENH', max_length=26, unique=True, verbose_name='ULID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ulid',
            field=models.CharField(default='01HWFK6AKM2H586XKC35F5TCKG', max_length=26, unique=True, verbose_name='ULID'),
        ),
    ]
