# Generated by Django 5.0.4 on 2024-04-25 12:52

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Nationality'),
        ),
    ]
