# Generated by Django 5.0.4 on 2024-04-25 12:53

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_dob_alter_customer_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Nationality'),
        ),
    ]
