# Generated by Django 5.0.4 on 2024-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_business_ulid_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='ulid',
            field=models.CharField(default='01HWFK6JSRNZ0RJ0EC5H1890HV', max_length=26, unique=True, verbose_name='ULID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ulid',
            field=models.CharField(default='01HWFK6JSPVRNS96G8PVECDJH1', max_length=26, unique=True, verbose_name='ULID'),
        ),
    ]
