# Generated by Django 5.0.4 on 2024-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_business_ulid_alter_customer_ulid_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='ulid',
            field=models.CharField(default='01HWFS4CKN0EEZXZS07MQYE62K', max_length=26, unique=True, verbose_name='ULID'),
        ),
    ]
