# Generated by Django 5.0.4 on 2024-04-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customer_created_at_alter_business_ulid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='ulid',
            field=models.CharField(default='01HWFTWHC7CMKQBQ08Z5EBEQG8', max_length=26, unique=True, verbose_name='ULID'),
        ),
    ]
